[tool.ruff.lint]
select = [
    "FAST001",
    "FAST002",
    "FAST003",
    "ANN002",
    "ANN003",
    "ANN202",
    "ANN204",
    "ANN205",
    "ANN206",
    "ASYNC100",
    "ASYNC105",
    "ASYNC115",
    "ASYNC210",
    "ASYNC220",
    "ASYNC221",
    "ASYNC222",
    "ASYNC230",
    "ASYNC251",
    "S105",
    "S106",
    "S107",
    "S110",
    "S112",
    "S113",
    "S607",
    "BLE001",
    "B002",
    "B003",
    "B004",
    "B005",
    "B007",
    "B008",
    "B009",
    "B010",
    "B011",
    "B012",
    "B013",
    "B014",
    "B015",
    "B016",
    "B017",
    "B021",
    "B027",
    "B028",
    "B029",
    "B032",
    "B033",
    "B034",
    "B039",
    "B905",
    "A001",
    "A002",
    "A003",
    "A004",
    "A005",
    "A006",
    "COM812",
    "COM818",
    "COM819",
    "C400",
    "C401",
    "C402",
    "C403",
    "C404",
    "C405",
    "C406",
    "C408",
    "C409",
    "C410",
    "C411",
    "C413",
    "C414",
    "C416",
    "C417",
    "C418",
    "C419",
    "C420",
    "EM101",
    "EM102",
    "EM103",
    "EXE004",
    "FA102",
    "ISC001",
    "ISC002",
    "ISC003",
    "ICN001",
    "ICN002",
    "LOG001",
    "LOG002",
    "LOG009",
    "G010",
    "PIE790",
    "PIE794",
    "PIE796",
    "PIE800",
    "PIE804",
    "PIE807",
    "PIE808",
    "PIE810",
    "T201",
    "T203",
    "PYI001",
    "PYI009",
    "PYI010",
    "PYI011",
    "PYI012",
    "PYI013",
    "PYI014",
    "PYI015",
    "PYI016",
    "PYI017",
    "PYI018",
    "PYI019",
    "PYI020",
    "PYI021",
    "PYI024",
    "PYI025",
    "PYI026",
    "PYI029",
    "PYI030",
    "PYI032",
    "PYI033",
    "PYI034",
    "PYI036",
    "PYI041",
    "PYI042",
    "PYI043",
    "PYI044",
    "PYI053",
    "PYI054",
    "PYI055",
    "PYI058",
    "PYI062",
    "PYI064",
    "PT001",
    "PT003",
    "PT006",
    "PT007",
    "PT009",
    "PT014",
    "PT018",
    "PT022",
    "PT023",
    "PT024",
    "PT025",
    "PT026",
    "PT027",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "Q004",
    "RET501",
    "RET502",
    "RET503",
    "RET504",
    "RET505",
    "RET506",
    "RET507",
    "RET508",
    "SIM101",
    "SIM102",
    "SIM103",
    "SIM105",
    "SIM108",
    "SIM109",
    "SIM110",
    "SIM112",
    "SIM114",
    "SIM115",
    "SIM117",
    "SIM118",
    "SIM201",
    "SIM202",
    "SIM208",
    "SIM210",
    "SIM211",
    "SIM212",
    "SIM220",
    "SIM221",
    "SIM222",
    "SIM223",
    "SIM300",
    "SIM401",
    "SIM905",
    "SIM910",
    "SIM911",
    "TD006",
    "TC001",
    "TC002",
    "TC003",
    "TC004",
    "TC005",
    "TC006",
    "TC007",
    "FLY002",
    "I002",
    "NPY001",
    "NPY003",
    "NPY201",
    "PD003",
    "PD004",
    "PD007",
    "PD008",
    "PD009",
    "PD010",
    "PD013",
    "N801",
    "N802",
    "N803",
    "N804",
    "N805",
    "N806",
    "N807",
    "N811",
    "N812",
    "N813",
    "N814",
    "N815",
    "N816",
    "PERF101",
    "PERF102",
    "PERF203",
    "PERF401",
    "PERF403",
    "E101",
    "E401",
    "E501",
    "E703",
    "E711",
    "E712",
    "E713",
    "E714",
    "E731",
    "W291",
    "W292",
    "W293",
    "W605",
    "D101",
    "D102",
    "D105",
    "D106",
    "D107",
    "D200",
    "D201",
    "D203",
    "D204",
    "D207",
    "D208",
    "D210",
    "D211",
    "D212",
    "D213",
    "D214",
    "D215",
    "D300",
    "D301",
    "D400",
    "D403",
    "D405",
    "D406",
    "D407",
    "D408",
    "D409",
    "D410",
    "D411",
    "D412",
    "D413",
    "D414",
    "D415",
    "D416",
    "D418",
    "D419",
    "F401",
    "F402",
    "F403",
    "F405",
    "F406",
    "F407",
    "F501",
    "F502",
    "F503",
    "F504",
    "F505",
    "F506",
    "F507",
    "F509",
    "F521",
    "F522",
    "F523",
    "F524",
    "F525",
    "F541",
    "F601",
    "F602",
    "F632",
    "F702",
    "F704",
    "F706",
    "F811",
    "F823",
    "F841",
    "F842",
    "F901",
    "PGH004",
    "PLC0132",
    "PLC0208",
    "PLC0414",
    "PLC1802",
    "PLE0116",
    "PLE0241",
    "PLE1519",
    "PLE1520",
    "PLE2510",
    "PLE2512",
    "PLE2513",
    "PLE2514",
    "PLE2515",
    "PLR0206",
    "PLR0402",
    "PLR1711",
    "PLR1714",
    "PLR1716",
    "PLR1722",
    "PLR1730",
    "PLR1736",
    "PLR2044",
    "PLR5501",
    "PLW0120",
    "PLW0127",
    "PLW0128",
    "PLW0129",
    "PLW0133",
    "PLW0245",
    "PLW1507",
    "PLW1510",
    "PLW3301",
    "UP001",
    "UP003",
    "UP004",
    "UP005",
    "UP006",
    "UP007",
    "UP008",
    "UP009",
    "UP010",
    "UP011",
    "UP012",
    "UP013",
    "UP014",
    "UP015",
    "UP017",
    "UP018",
    "UP019",
    "UP020",
    "UP021",
    "UP022",
    "UP023",
    "UP024",
    "UP025",
    "UP026",
    "UP028",
    "UP029",
    "UP030",
    "UP031",
    "UP032",
    "UP033",
    "UP034",
    "UP035",
    "UP036",
    "UP037",
    "UP039",
    "UP040",
    "UP041",
    "UP043",
    "UP044",
    "FURB105",
    "FURB129",
    "FURB136",
    "FURB161",
    "FURB163",
    "FURB167",
    "FURB168",
    "FURB169",
    "FURB177",
    "FURB181",
    "FURB187",
    "FURB188",
    "RUF005",
    "RUF007",
    "RUF010",
    "RUF013",
    "RUF015",
    "RUF017",
    "RUF019",
    "RUF020",
    "RUF021",
    "RUF022",
    "RUF023",
    "RUF024",
    "RUF026",
    "RUF030",
    "RUF032",
    "RUF033",
    "RUF041",
    "RUF046",
    "RUF051",
    "RUF100",
    "RUF101",
    "TRY002",
    "TRY004",
    "TRY201",
    "TRY400"
]
[tool.ruff]
line-length = 120
